# === Identification du projet sur SonarCloud ===
sonar.projectKey=BaptisteNebout_portfolio
sonar.organization=baptistenebout
sonar.projectName=portfolio
sonar.projectVersion=1.0

# === Répertoires sources ===
sonar.sources=.

# === Exclusions (fichiers générés) ===
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/coverage/**

# === Encodage ===
sonar.sourceEncoding=UTF-8

# === Tests & Coverage ===
# (Si tu génères des tests Jest ou Vitest plus tard)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
